name: Build APK

on:
  push:
    branches:
      - main   # o master, según el nombre de tu rama principal
  workflow_dispatch:   # permite lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk git zip unzip
          pip install buildozer cython==0.29.36 setuptools==58.0.4

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-apk
          path: bin/*.apk
